### PR TITLE
WIP - re-init app by the vitejs (+fix eslint and typescript warnings)

### LINKED ISSUE #107: Init jest
Move from CRA to the vitejs require new Jest initialization.
branch: https://github.com/argo22com/garbage_map/tree/feature/switch-to-the-vitejs

### PR DESCRIPTION
**Pull request by gynekolog**
Move from the https://github.com/facebook/create-react-app stack to the https://github.com/vitejs/vite.

### CODE REVIEW

**Comment by gynekolog** [comment]
@wodCZ
Take a look on the line https://github.com/argo22com/garbage_map/blob/master/src/datasource/index.ts#L51 , please. Eslint reports an error: `Promise executor functions should not be async.(no-async-promise-executor)`.
I didn't want to reach your code.

btw, before commit reinstall pre-commit hook created by `husky` 'cause there's [issue](https://github.com/typicode/husky/issues/875) with the new `husky` version:
```
$ rm -rf .git/hooks && ln -s ../.husky .git/hooks
```

**Comment by wodCZ** [comment]
@gynekolog fixed the issues along with vercel deployment.

By the way, why were we using absolute imports?
```ts
import { Map } from "components/Map";
import { IconSpot } from "components/IconSpot";
import { Filters as TFilters, getSpots, Spot } from "datasource";
```

it was causing issues in the tests (I guess it's no-longer supported in upgraded jest?)

**Comment by gynekolog** [comment]
@wodCZ Absolute imports are more readable for me especially with the import sorting (not implemented yet).

Didn't know about absolute paths in jest. But the issue can be solved by jest configuration in `package.json`:
```
"jest": {
    "modulePaths": [
      "<rootDir>/src/"
    ]
  },
```
doc: https://jestjs.io/docs/configuration#modulepaths-arraystring

Are you OK with "fix" or are absolute imports in jest reason to switch to the relative imports?

**Comment by wodCZ** [comment]
Not a fan of absolute imports, for these reasons:
- it hides the immediate distinction between 3rd party package & local code (is it my datasource or is it https://www.npmjs.com/package/datasource ?). What should I do if I want to create a directory which is named like a package? (e.g. we have a `table` package installed - now I can't have my own table)
- makes refactoring harder & messy I guess?

But since we already use absolute imports across the app, I'm ok with rolling my changes back & using the Jest config (if it works).

**Comment by gynekolog** [comment]
@wodCZ OK, I have no extra reasons to use absolute imports.
But switch from absolute imports to the relative in a separate pull request, please.
https://github.com/argo22com/garbage_map/projects/2#card-57361289

**Pull request merged**
